name: Publish

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: '8.0.x'

defaults:
  run:
    working-directory: VALORez

jobs:
  release:
    name: Release (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Package
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="app-$tag-win-x64"

          # Build
          dotnet publish --framework net8.0 --runtime win-x64 -c Release -o "$release_name"

          # Pack to zip
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "app*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
